services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Berlin
      - UMASK=022
    volumes:
      - /mnt/appdata/radarr:/config
      - /mnt/Media/Movies:/movies
      - /mnt/Media/Downloads:/downloads
    ports:
      - "7878:7878"
    labels:
      flame.type: application
      flame.name: Radarr
      flame.icon: movie
      flame.url: https://movies.szakoswulkan.eu
    restart: unless-stopped