services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Berlin
      - UMASK=022
    volumes:
      - /mnt/appdata/homeassistant:/config
    labels:
      flame.type: application
      flame.name: Home Assistant
      flame.icon: home-assistant
      flame.url: https://nexus.szakoswulkan.eu
    restart: unless-stopped