services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /opt/appdata/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Stockholm
    labels:
      flame.type: application
      flame.name: Uptime Kuma
      flame.icon: heart-pulse
      flame.url: https://kuma.szakoswulkan.eu
    healthcheck:
      test: ["CMD-SHELL", "extra/healthcheck"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
