services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    user: "99:100"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/appdata/audiobookshelf:/config
      - /mnt/appdata/audiobookshelf/metadata:/metadata
      - /mnt/Media/Audiobooks:/audiobooks
      - /mnt/Media/Podcasts:/podcasts
    ports:
      - "13378:80"
    labels:
      flame.type: application
      flame.name: Audiobookshelf
      flame.icon: book-music
      flame.url: https://sound.szakoswulkan.eu
    restart: unless-stopped